### ISSUE TITLE
[Feature Request] Add "Fus-Ro-Dah!!"

### ISSUE THREAD

**Issue by mschoenUsp** [sirrus86/S86Powers#4]
Implement a power that just pushes away every mob or player in front of you, similar to the bow's "punch" or the sword's "knockback" enchantments. Only stronger.

In case you're wondering what "Fus-Ro-Dah" means, it's the name of the most (in)famous dragon shout in Skyrim.

**Comment by sirrus86** [comment]
There's a similar power called Aero Blade that does this, though not with as much punch as you're probably wanting. Certainly something I can add in the future.

In the meantime I'd suggest you submit this idea to the [S86 Powers Discord](https://discord.gg/3MzPwUM5), as well as any others you think up in the future.
